
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 03 19:29:24 BRST 2017
//----------------------------------------------------

package lua;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FECHA_COLCHETES = 34;
  public static final int NOME = 2;
  public static final int NUMERO = 55;
  public static final int RESTO = 42;
  public static final int FUNCAO = 17;
  public static final int LACO_FACA = 6;
  public static final int SOMA = 37;
  public static final int COMENTARIO_CURTO = 5;
  public static final int DIFERENTE = 49;
  public static final int IGUAL_COMPARATIVO = 48;
  public static final int MULTIPLICACAO = 39;
  public static final int ABRE_PARENTESIS = 51;
  public static final int ATE_LIMITE_LACO = 10;
  public static final int STRING_LUA = 3;
  public static final int OPERADOR_E = 25;
  public static final int DOIS_PONTOS = 31;
  public static final int DEFINICAO_LOCAL = 19;
  public static final int VIRGULA = 32;
  public static final int NEGACAO = 27;
  public static final int PONTO = 30;
  public static final int LACO_PARA = 15;
  public static final int QUEBRA_LACO = 21;
  public static final int REPETICAO = 9;
  public static final int ENTAO = 12;
  public static final int EXPONENCIACAO = 41;
  public static final int RETORNO = 20;
  public static final int FECHA_PARENTESIS = 52;
  public static final int SE_CONDICIONAL = 11;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int OPERADOR_OU = 26;
  public static final int SENAO = 14;
  public static final int MAIOR_IGUAL_QUE = 47;
  public static final int NULO = 22;
  public static final int MAIOR_QUE = 46;
  public static final int DIVISAO = 40;
  public static final int CONCATENAR_STRING = 43;
  public static final int COMENTARIO_EM_BLOCO = 4;
  public static final int VALOR_FALSO = 23;
  public static final int ABRE_COLCHETES = 33;
  public static final int SENAO_SE = 13;
  public static final int FUNCAO_LOCAL = 18;
  public static final int PONTO_E_VIRGULA = 36;
  public static final int brancos = 28;
  public static final int ATRIBUICAO = 29;
  public static final int ABRE_CHAVES = 53;
  public static final int MENOR_QUE = 44;
  public static final int FIM_DO_LACO = 7;
  public static final int DENTRO = 16;
  public static final int VALOR_VERDADEIRO = 24;
  public static final int FECHA_CHAVES = 54;
  public static final int MENOR_IGUAL_QUE = 45;
  public static final int EXPRESSAO_VARARG = 35;
  public static final int SUBTRACAO = 38;
  public static final int LACO_ENQUANTO = 8;
  public static final int TAMANHO = 50;
}

