
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Dec 16 13:15:40 BRST 2016
//----------------------------------------------------

package lua;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int FECHA_COLCHETES = 52;
  public static final int NOME = 47;
  public static final int NUMERO = 45;
  public static final int RESTO = 7;
  public static final int FUNCAO = 28;
  public static final int LACO_FACA = 22;
  public static final int SOMA = 2;
  public static final int DIFERENTE = 19;
  public static final int MULTIPLICACAO = 4;
  public static final int IGUAL_COMPARATIVO = 17;
  public static final int ABRE_PARENTESIS = 42;
  public static final int STRING_LUA = 46;
  public static final int ATE_LIMITE_LACO = 37;
  public static final int OPERADOR_E = 20;
  public static final int CONCATERNAR_STRING = 12;
  public static final int DOIS_PONTOS = 8;
  public static final int DEFINICAO_LOCAL = 31;
  public static final int VIRGULA = 49;
  public static final int NEGACAO = 33;
  public static final int PONTO = 9;
  public static final int LACO_PARA = 27;
  public static final int QUEBRA_LACO = 10;
  public static final int REPETICAO = 34;
  public static final int ENTAO = 35;
  public static final int EXPONENCIACAO = 6;
  public static final int RETORNO = 39;
  public static final int FECHA_PARENTESIS = 43;
  public static final int SE_CONDICIONAL = 29;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int OPERADOR_OU = 21;
  public static final int SENAO = 24;
  public static final int NULO = 32;
  public static final int MAIOR_IGUAL_QUE = 15;
  public static final int MAIOR_QUE = 14;
  public static final int DIVISAO = 5;
  public static final int FACA = 11;
  public static final int VALOR_FALSO = 26;
  public static final int ABRE_COLCHETES = 51;
  public static final int SENAO_SE = 23;
  public static final int PONTO_E_VIRGULA = 50;
  public static final int ATRIBUICAO = 18;
  public static final int ABRE_CHAVES = 40;
  public static final int MENOR_QUE = 13;
  public static final int FIM_DO_LACO = 25;
  public static final int DENTRO = 30;
  public static final int VALOR_VERDADEIRO = 36;
  public static final int EXPRESSAO_VARARG = 44;
  public static final int FECHA_CHAVES = 41;
  public static final int MENOR_IGUAL_QUE = 16;
  public static final int LACO_ENQUANTO = 38;
  public static final int SUBTRACAO = 3;
  public static final int TAMANHO = 48;
}

